@baseUrl = http://localhost:3333

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Lucas",
  "email": "example2@gmail.com",
  "password": "123456"
}

###
# @name create_user
GET {{baseUrl}}/users


###
# @name create_user
PATCH  {{baseUrl}}/users
Content-Type: application/json
{
  "id": "65d36fb7f0fb2f38d7d575ad",
  "name": "Rocha"
}
